version: "3.3"

services:
  app:
    stdin_open: true
    build: 
      context: . 
      dockerfile: DockerfileClient
    image: camila12ospina/cevudem2-app
    ports:
      - "5173:5173"
   
  database:
    image: "mysql:latest"
    restart: always
    volumes:
      - "./mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret 
    ports:
      - "3308:3306"
    expose:
      - 3308
    
  api:
    stdin_open: true
    build: 
      context: .
      dockerfile: DockerfileServer
    image: camila12ospina/cevudem2-api 
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - "database: database.api"

