version: "3.3"

services:
  app:
    stdin_open: true
    build: 
      context: . 
      dockerfile: DockerfileClient
    image: camila12ospina/cevudem:app
    ports:
      - "5173:5173"
   
  database:
    stdin_open: true
    build: 
      context: .
      dockerfile: DockerfileDatabase
    image: camila12ospina/cevudem:database
    restart: always
    ports:
      - "3308:3306"
    
  api:
    stdin_open: true
    build: 
      context: .
      dockerfile: DockerfileServer
    image: camila12ospina/cevudem:api
    ports:
      - "3000:3000"
    depends_on:
      - database
    links:
      - "database: database.api"

