name: Docker

on:
  push:
    branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push Docker images
      run: |
        for service in $(docker-compose config --services); do
          image_name=$(docker-compose images $service --format "{{.Repository}}")
          image_tag=$(docker-compose images $service --format "{{.Tag}}")
          repo_name=$(echo $image_name | awk -F / '{print $NF}')
          docker-compose build $service
          docker tag $image_name:$image_tag $DOCKERHUB_USERNAME/$repo_name:$image_tag
          docker push $DOCKER_USERNAME/$repo_name:$image_tag
        done
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}